# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://kevinlq.github.io
date_format: "ordinal"
title: 鹅卵石
subtitle: "鹅卵石的后花园"
description: "鹅卵石的个人博客"
keywords: 鹅卵石, devstone
timezone: China/XiAn
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: kevin li
organization: zhihu.com
organization_url: https://www.zhihu.com/people/kevinlq/activities
github_username: kevinlq
location: XiAn, China
email: kevinlq0912@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /categories/
    label: 分类
  -
    href: /project/
    label: 项目
  -
    href: /resourse/
    label: 资源
  -
    href: /reading/
    label: 阅读
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    reading:
        output: true
        permalink: /reading/:path/
    life:
        output: true
        permalink: /life:/:path/
    project:
        output: true
        permalink: /project:/:path/

repository: kevinlq/kevinlq.github.com

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: kevinlq
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: kevinlq
    repo: blog-comments
    oauth:
        client_id: 5d3c691d2add5afc5824
        client_secret: 1a902a29f37057e5f5d81a65f3f0b3fd17c671a4
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: kevinlq
    repo: blog-comments
    clientID: 5d3c691d2add5afc5824
    clientSecret: 1a902a29f37057e5f5d81a65f3f0b3fd17c671a4
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
# 下面的百度分析ID请换成你自己的 !!!!
baidu:
    analytics_id: f9a2a52ccc103ed91088462c5836c854
